[[crypto]]
= Spring Security Crypto Module

[[spring-security-crypto-introduction]]
* provides support for
    ** symmetric encryption,
    ** key generation,
    ** password encoding
* -- distributed as -- part of the core module

[[spring-security-crypto-encryption]]
== Encryptors
* `org.springframework.security.crypto.encrypt.Encryptors`
    ** 's factory methods -- for -- constructing symmetric encryptors
    ** lets you create
        *** `org.springframework.security.crypto.encrypt.BytesEncryptor` / -- encrypt data in -- raw `byte[]` form
        *** `org.springframework.security.crypto.encrypt.TextEncryptor` / -- encrypt -- text strings
    ** are thread-safe

[[spring-security-crypto-encryption-bytes]]
=== BytesEncryptor
* alternatives
    ** -- via -- `Encryptors.stronger()`
+
.BytesEncryptor
[tabs]
======
Java::
+
[source,java,role="primary"]
----
Encryptors.stronger("password", "salt");
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
Encryptors.stronger("password", "salt")
----
======

        *** 👀recommended one 👀
        *** salt -- can be generated, by using a -- `KeyGenerator`:
+
.Generating a key
[tabs]
======
Java::
+
[source,java,role="primary"]
----
String salt = KeyGenerators.string().generateKey(); // generates a random 8-byte salt that is then hex-encoded
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val salt = KeyGenerators.string().generateKey() // generates a random 8-byte salt that is then hex-encoded
----
======

    ** -- via -- `Encryptors.standard()`

[[spring-security-crypto-encryption-text]]
=== TextEncryptor
* -- via -- the `Encryptors.text()`
+
.TextEncryptor
[tabs]
======
Java::
+
[source,java,role="primary"]
----
Encryptors.text("password", "salt");
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
Encryptors.text("password", "salt")
----
======

[[spring-security-crypto-keygenerators]]
== Key Generators

* `org.springframework.security.crypto.keygen.KeyGenerators`
    ** 's factory methods -- for -- constructing key generators
    ** let's you create
        *** `org.springframework.security.crypto.keygen.BytesKeyGenerator` / generate `byte[]` keys
        *** `org.springframework.security.crypto.keygen.StringKeyGenerator` / generate `string` keys
    ** thread-safe

=== BytesKeyGenerator
* -- via -- `KeyGenerators.secureRandom()` factory methods /
    ** backed by a `SecureRandom` instance
    ** key length = 8 bytes
+
.BytesKeyGenerator
[tabs]
======
Java::
+
[source,java,role="primary"]
----
BytesKeyGenerator generator = KeyGenerators.secureRandom();
byte[] key = generator.generateKey();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
val generator = KeyGenerators.secureRandom()
val key = generator.generateKey()
----
======


* -- via -- `KeyGenerators.secureRandom(int keyLength)`
+
.KeyGenerators.secureRandom
[tabs]
======
Java::
+
[source,java,role="primary"]
----
KeyGenerators.secureRandom(16);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
KeyGenerators.secureRandom(16)
----
======

* -- via -- `KeyGenerators.shared(int keyLength)`
    /
    ** 👀SAME key is returned ALWAYS 👀
+
.KeyGenerators.shared
[tabs]
======
Java::
+
[source,java,role="primary"]
----
KeyGenerators.shared(16);
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
KeyGenerators.shared(16)
----
======

=== StringKeyGenerator
* -- via -- `KeyGenerators.string()` /
    ** construct an 8-byte, `SecureRandom` `KeyGenerator`
    ** return String / EACH hex-encoded key
+
.StringKeyGenerator
[tabs]
======
Java::
+
[source,java,role="primary"]
----
KeyGenerators.string();
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
KeyGenerators.string()
----
======

[[spring-security-crypto-passwordencoders]]
== Password Encoding
The password package of the `spring-security-crypto` module provides support for encoding passwords.
`PasswordEncoder` is the central service interface and has the following signature:

[source,java]
----
public interface PasswordEncoder {
	String encode(CharSequence rawPassword);

	boolean matches(CharSequence rawPassword, String encodedPassword);

	default boolean upgradeEncoding(String encodedPassword) {
		return false;
	}
}
----

The `matches` method returns true if the `rawPassword`, once encoded, equals the `encodedPassword`.
This method is designed to support password-based authentication schemes.

The `BCryptPasswordEncoder` implementation uses the widely supported "`bcrypt`" algorithm to hash the passwords.
Bcrypt uses a random 16-byte salt value and is a deliberately slow algorithm, to hinder password crackers.
You can tune the amount of work it does by using the `strength` parameter, which takes a value from 4 to 31.
The higher the value, the more work has to be done to calculate the hash.
The default value is `10`.
You can change this value in your deployed system without affecting existing passwords, as the value is also stored in the encoded hash.
The following example uses the `BCryptPasswordEncoder`:

.BCryptPasswordEncoder
[tabs]
======
Java::
+
[source,java,role="primary"]
----

// Create an encoder with strength 16
BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(16);
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

Kotlin::
+
[source,kotlin,role="secondary"]
----

// Create an encoder with strength 16
val encoder = BCryptPasswordEncoder(16)
val result: String = encoder.encode("myPassword")
assertTrue(encoder.matches("myPassword", result))
----
======

The `Pbkdf2PasswordEncoder` implementation uses PBKDF2 algorithm to hash the passwords.
To defeat password cracking, PBKDF2 is a deliberately slow algorithm and should be tuned to take about .5 seconds to verify a password on your system.
The following system uses the `Pbkdf2PasswordEncoder`:


.Pbkdf2PasswordEncoder
[tabs]
======
Java::
+
[source,java,role="primary"]
----
// Create an encoder with all the defaults
Pbkdf2PasswordEncoder encoder = Pbkdf2PasswordEncoder.defaultsForSpringSecurity_v5_8();
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
// Create an encoder with all the defaults
val encoder = Pbkdf2PasswordEncoder.defaultsForSpringSecurity_v5_8()
val result: String = encoder.encode("myPassword")
assertTrue(encoder.matches("myPassword", result))
----
======
