[[anonymous]]
= Anonymous Authentication


[[anonymous-overview]]
== Overview

* "`deny-by-default`" stance
    ** 👁️ recommended security practice 👁️
    ** == explicitly specify what is allowed & disallow everything else
* for web applications
    ** if you force authentication for 👁️few URLs 👁️ -> you can define access configuration attributes |
        *** these specific URLs -- via --
            **** `ROLE_SOMETHING` by default + certain exceptions to this rule
            **** omit these pages from the filter chain entirely
        *** (rather than) | every secured resource
* anonymous authentication
    ** "`anonymously authenticated`" user == (conceptually) unauthenticated user
    ** Spring Security's anonymous authentication
        *** provides
            **** convenient way -- to configure -- your access-control attributes
        *** servlet API calls
            **** _Example:_ `getCallerPrincipal`
            **** return null -- even though there is an anonymous authentication object | `SecurityContextHolder`
    ** uses
        *** "`anonymously authenticated`" users
        *** auditing interceptor queries the `SecurityContextHolder` -- to identify -- which principal / responsible for a given operation
            **** Reason: 🧠 if the classes know that `SecurityContextHolder` always contains an `Authentication` object / never contains `null` -> Classes authored more robustly 🧠

[[anonymous-config]]
== Configuration

* 👁️ if you use the HTTP configuration ( ? introduced in Spring Security 3.0) -> Anonymous Authentication support provided automatically 👁️
* `<anonymous>`
    ** := element /
        *** -- allows -- customizing or disabling it
* if you are using traditional bean configuration -> You need to configure the beans
* required classes -- to provide -- anonymous authentication feature
    ** `AnonymousAuthenticationToken`
        *** implementation of `Authentication`
        *** stores the `GrantedAuthority` instances / -- apply to -- the anonymous principal
    ** `AnonymousAuthenticationProvider`
        *** chained into the `ProviderManager`
            **** -> `AnonymousAuthenticationToken` instances are accepted
        *** if the scenario allows constructing the `Authentication` object (_Example:_ RMI invocation calls) -> you should use a customized `ProviderManager` / omits the anonymous provider -- rather than sharing the one / you use for your HTTP authentication mechanisms --
        *** _Example:_ `key` is shared with the filter

    <bean id="anonymousAuthenticationProvider" class="org.springframework.security.authentication.AnonymousAuthenticationProvider">
    <property name="key" value="foobar"/>
    </bean>

    ** `AnonymousAuthenticationFilter`
        *** chained after the normal authentication mechanisms
        *** if there is NO existing `Authentication` | `SecurityContextHolder` -> adds automatically an `AnonymousAuthenticationToken` | `SecurityContextHolder`
        *** _Example:_ `key` is shared with the provider

    <bean id="anonymousAuthFilter" class="org.springframework.security.web.authentication.AnonymousAuthenticationFilter">
    <property name="key" value="foobar"/>
    <property name="userAttribute" value="anonymousUser,ROLE_ANONYMOUS"/>
    </bean>

TODO:


====

The `userAttribute` is expressed in the form of `usernameInTheAuthenticationToken,grantedAuthority[,grantedAuthority]`.
The same syntax is used after the equals sign for the `userMap` property of `InMemoryDaoImpl`.

As explained earlier, the benefit of anonymous authentication is that all URI patterns can have security applied to them, as the following example shows:

[source,xml]
----
<bean id="filterSecurityInterceptor"
	class="org.springframework.security.web.access.intercept.FilterSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="httpRequestAccessDecisionManager"/>
<property name="securityMetadata">
	<security:filter-security-metadata-source>
	<security:intercept-url pattern='/index.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/hello.htm' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/logoff.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/login.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/**' access='ROLE_USER'/>
	</security:filter-security-metadata-source>" +
</property>
</bean>
----

[[anonymous-auth-trust-resolver]]
== AuthenticationTrustResolver
Rounding out the anonymous authentication discussion is the `AuthenticationTrustResolver` interface, with its corresponding `AuthenticationTrustResolverImpl` implementation.
This interface provides an `isAnonymous(Authentication)` method, which allows interested classes to take into account this special type of authentication status.
The `ExceptionTranslationFilter` uses this interface in processing `AccessDeniedException` instances.
If an `AccessDeniedException` is thrown and the authentication is of an anonymous type, instead of throwing a 403 (forbidden) response, the filter, instead, commences the `AuthenticationEntryPoint` so that the principal can authenticate properly.
This is a necessary distinction. Otherwise, principals would always be deemed "`authenticated`" and never be given an opportunity to login through form, basic, digest, or some other normal authentication mechanism.

We often see the `ROLE_ANONYMOUS` attribute in the earlier interceptor configuration replaced with `IS_AUTHENTICATED_ANONYMOUSLY`, which is effectively the same thing when defining access controls.
This is an example of the use of the `AuthenticatedVoter`, which we cover in the xref:servlet/authorization/architecture.adoc#authz-authenticated-voter[authorization chapter].
It uses an `AuthenticationTrustResolver` to process this particular configuration attribute and grant access to anonymous users.
The `AuthenticatedVoter` approach is more powerful, since it lets you differentiate between anonymous, remember-me, and fully authenticated users.
If you do not need this functionality, though, you can stick with `ROLE_ANONYMOUS`, which is processed by Spring Security's standard `RoleVoter`.

[[anonymous-auth-mvc-controller]]
== Getting Anonymous Authentications with Spring MVC

https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-arguments[Spring MVC resolves parameters of type `Principal`] using its own argument resolver.

This means that a construct like this one:

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public String method(Authentication authentication) {
	if (authentication instanceof AnonymousAuthenticationToken) {
		return "anonymous";
	} else {
		return "not anonymous";
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun method(authentication: Authentication?): String {
    return if (authentication is AnonymousAuthenticationToken) {
        "anonymous"
    } else {
        "not anonymous"
    }
}
----
======

will always return "not anonymous", even for anonymous requests.
The reason is that Spring MVC resolves the parameter using `HttpServletRequest#getPrincipal`, which is `null` when the request is anonymous.

If you'd like to obtain the `Authentication` in anonymous requests, use `@CurrentSecurityContext` instead:

.Use CurrentSecurityContext for Anonymous requests
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@GetMapping("/")
public String method(@CurrentSecurityContext SecurityContext context) {
	return context.getAuthentication().getName();
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun method(@CurrentSecurityContext context : SecurityContext) : String =
		context!!.authentication!!.name
----
======
